export const bmi_exercises = [
  {
    id: "1",
    name: "Backword Camel Stretch",
    repeat: "Hold for 30 seconds",
    duration: "30 seconds",
    image: require("../assets/bmi/Backword Camel Stretch.gif"),
  },
  {
    id: "2",
    name: "Bridge",
    repeat: "12 reps",
    duration: "40 seconds",
    image: require("../assets/bmi/Bridge.webp"),
  },
  {
    id: "3",
    name: "Cobra Abdominal Stretch",
    repeat: "Hold for 20 seconds",
    duration: "20 seconds",
    image: require("../assets/bmi/Cobra Abdominal Stretch.webp"),
  },
  {
    id: "4",
    name: "Dana-scruggs-fitness",
    repeat: "10 reps per leg",
    duration: "50 seconds",
    image: require("../assets/bmi/Dana-scruggs-fitness.gif"),
  },
  {
    id: "5",
    name: "Jumping Jacks",
    repeat: "Perform for 30 seconds",
    duration: "30 seconds",
    image: require("../assets/bmi/Jumping Jacks.gif"),
  },
  {
    id: "6",
    name: "Knee-To-Chest Lower Back Stretch",
    repeat: "Hold for 20 seconds per side",
    duration: "40 seconds",
    image: require("../assets/bmi/Knee-To-Chest Lower Back Stretch.webp"),
  },
  {
    id: "7",
    name: "Kneeling Shoulder Press",
    repeat: "12 reps",
    duration: "35 seconds",
    image: require("../assets/bmi/Kneeling Shoulder Press.gif"),
  },
  {
    id: "8",
    name: "Leg Lifts",
    repeat: "15 reps",
    duration: "45 seconds",
    image: require("../assets/bmi/Leg Lifts.webp"),
  },
  {
    id: "9",
    name: "Mountain Climbers",
    repeat: "20 reps",
    duration: "30 seconds",
    image: require("../assets/bmi/Mountain Climbers.gif"),
  },
  {
    id: "10",
    name: "One-Arm Push-Up",
    repeat: "8 reps per arm",
    duration: "40 seconds",
    image: require("../assets/bmi/One-Arm Push-Up.webp"),
  },
  {
    id: "11",
    name: "Pigeon",
    repeat: "Hold for 30 seconds per side",
    duration: "60 seconds",
    image: require("../assets/bmi/Pigeon.webp"),
  },
  {
    id: "12",
    name: "Push Ups",
    repeat: "15 reps",
    duration: "40 seconds",
    image: require("../assets/bmi/Push Ups.webp"),
  },
  {
    id: "13",
    name: "Seated Shoulder Press",
    repeat: "15 reps",
    duration: "45 seconds",
    image: require("../assets/bmi/Seated Shoulder Press.webp"),
  },
  {
    id: "14",
    name: "Single Leg Bridge",
    repeat: "10 reps per leg",
    duration: "45 seconds",
    image: require("../assets/bmi/Single Leg Bridge.webp"),
  },
  {
    id: "15",
    name: "Squat",
    repeat: "20 reps",
    duration: "50 seconds",
    image: require("../assets/bmi/Squat.webp"),
  },
  {
    id: "16",
    name: "The Deadbug",
    repeat: "12 reps per side",
    duration: "45 seconds",
    image: require("../assets/bmi/The Deadbug.webp"),
  },
  {
    id: "17",
    name: "Weight Lifting",
    repeat: "10 reps",
    duration: "40 seconds",
    image: require("../assets/bmi/Weight Lifting.webp"),
  },
];

export const height_exercises = [
  {
    id: "1",
    name: "Reverse Crunches",
    repeat: "12 reps",
    duration: "25 seconds",
    image: require("../assets/height/20 Recerse Crunches.webp"),
  },
  {
    id: "2",
    name: "Cardio 2",
    repeat: "45 seconds",
    duration: "45 seconds",
    image: require("../assets/height/Cardio 2.webp"),
  },
  {
    id: "3",
    name: "Cobra Pose",
    repeat: "Hold for 30 seconds",
    duration: "30 seconds",
    image: require("../assets/height/Cobra-Pose.webp"),
  },
  {
    id: "4",
    name: "Jumping",
    repeat: "20 reps",
    duration: "30 seconds",
    image: require("../assets/height/Jumping.webp"),
  },
  {
    id: "5",
    name: "Long Jump",
    repeat: "10 reps per leg",
    duration: "40 seconds",
    image: require("../assets/height/Long Jump.webp"),
  },
  {
    id: "6",
    name: "Pullup Exercise",
    repeat: "Hold for 25 seconds",
    duration: "25 seconds",
    image: require("../assets/height/Pullup Exercise.webp"),
  },
  {
    id: "7",
    name: "Rope Jumping",
    repeat: "40 reps",
    duration: "45 seconds",
    image: require("../assets/height/Rope Jumping.webp"),
  },
  {
    id: "8",
    name: "Sit Ups With Rope",
    repeat: "12 reps",
    duration: "25 seconds",
    image: require("../assets/height/Sit Ups With Rope.webp"),
  },
  {
    id: "9",
    name: "Sit Ups",
    repeat: "15 reps",
    duration: "30 seconds",
    image: require("../assets/height/Sit Ups.webp"),
  },
  {
    id: "10",
    name: "Superman Pose",
    repeat: "Hold for 30 seconds",
    duration: "30 seconds",
    image: require("../assets/height/Sperman Pose.webp"),
  },
  {
    id: "11",
    name: "Standing Forward Bend",
    repeat: "Hold for 30 seconds",
    duration: "30 seconds",
    image: require("../assets/height/Standing Forward Bend.webp"),
  },
  {
    id: "12",
    name: "Switch Jumps",
    repeat: "15 reps",
    duration: "30 seconds",
    image: require("../assets/height/Switch Jumps.webp"),
  },
  {
    id: "13",
    name: "Toe Touch",
    repeat: "15 reps",
    duration: "30 seconds",
    image: require("../assets/height/Toe Touch.webp"),
  },
  {
    id: "14",
    name: "Triangle Pose",
    repeat: "Hold for 20 seconds per side",
    duration: "40 seconds",
    image: require("../assets/height/Triangle Pose.webp"),
  },
  {
    id: "15",
    name: "Vertical Leg Crunches",
    repeat: "15 reps",
    duration: "30 seconds",
    image: require("../assets/height/Vertical Leg Crunches.webp"),
  },
];
